import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Administrador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen justify-center items-center"
      >
        {children}
      </body>
    </html>
  );
}
